# Generated by Django 5.1.1 on 2026-09-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_admissionapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='application_number',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
