# Generated by Django 5.1.1 on 2026-09-23 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_add_application_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='desired_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_applications', to='portal.schoolclass'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='admission_documents/'),
        ),
    ]
