# Generated by Django 5.1.1 on 2026-09-23 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_extend_admission_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
