from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.PortalLoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("password-reset/", auth_views.PasswordResetView.as_view(template_name="registration/password_reset.html", email_template_name="registration/password_reset_email.txt"), name="password_reset"),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"), name="password_reset_confirm"),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"), name="password_reset_complete"),
    path("settings/password/", auth_views.PasswordChangeView.as_view(template_name="registration/password_change.html", success_url="/settings/password/done/"), name="password_change"),
    path("settings/password/done/", auth_views.PasswordChangeDoneView.as_view(template_name="registration/password_change_done.html"), name="password_change_done"),

    path("dashboard/", views.dashboard, name="dashboard"),
    path("admissions/apply/", views.admission_apply, name="admission_apply"),
    path("admissions/track/", views.admission_track, name="admission_track"),
    path("my-application/", views.my_application_status, name="my_application_status"),
    path("admissions/", views.admissions, name="admissions"),
    path("admissions/<int:pk>/", views.admission_detail, name="admission_detail"),
    path("admissions/<int:pk>/approve/", views.admission_approve, name="admission_approve"),
    path("admissions/<int:pk>/reject/", views.admission_reject, name="admission_reject"),
    path("students/", views.students, name="students"),
    path("students/add/", views.student_create, name="student_create"),
    path("students/<int:pk>/", views.student_detail, name="student_detail"),
    path("students/<int:pk>/edit/", views.student_edit, name="student_edit"),
    path("students/<int:pk>/toggle/", views.student_toggle, name="student_toggle"),
    path("teachers/", views.teachers, name="teachers"),
    path("teachers/add/", views.teacher_create, name="teacher_create"),
    path("teachers/<int:pk>/", views.teacher_detail, name="teacher_detail"),
    path("teachers/<int:pk>/edit/", views.teacher_edit, name="teacher_edit"),
    path("classes/", views.classes, name="classes"),
    path("classes/add/", views.class_create, name="class_create"),
    path("subjects/", views.subjects, name="subjects"),
    path("subjects/add/", views.subject_create, name="subject_create"),
    path("subjects/<int:pk>/edit/", views.subject_edit, name="subject_edit"),

    path("attendance/", views.attendance, name="attendance"),
    path("timetable/", views.timetable, name="timetable"),
    path("timetable/slots/add/", views.timetable_slot_create, name="timetable_slot_create"),
    path("timetable/slots/<int:pk>/edit/", views.timetable_slot_edit, name="timetable_slot_edit"),
    path("timetable/slots/<int:pk>/delete/", views.timetable_slot_delete, name="timetable_slot_delete"),
    path("assessments/", views.assessments, name="assessments"),
    path("assessments/add/", views.assessment_create, name="assessment_create"),
    path("assessments/<int:pk>/marks/", views.mark_entry, name="mark_entry"),
    path("results/", views.my_results, name="my_results"),
    path("students/<int:student_pk>/report-card/", views.report_card, name="report_card"),
    path("students/<int:student_pk>/report-card/download/", views.report_card_download, name="report_card_download"),
    path("assignments/", views.assignments, name="assignments"),
    path("assignments/add/", views.assignment_create, name="assignment_create"),
    path("assignments/<int:pk>/download/", views.assignment_attachment_download, name="assignment_attachment_download"),
    path("assignments/<int:pk>/submit/", views.assignment_submit, name="assignment_submit"),
    path("submissions/<int:pk>/download/", views.submission_download, name="submission_download"),
    path("learning-materials/", views.learning_materials, name="learning_materials"),
    path("learning-materials/add/", views.material_create, name="material_create"),

    path("finance/", views.finance, name="finance"),
    path("finance/invoices/add/", views.invoice_create, name="invoice_create"),
    path("finance/payments/add/", views.payment_create, name="payment_create"),
    path("finance/receipts/<int:pk>/", views.receipt, name="receipt"),
    path("finance/receipts/<int:pk>/download/", views.receipt_download, name="receipt_download"),
    path("fees/", views.my_fees, name="my_fees"),
    path("fees/<int:student_pk>/", views.my_fees, name="student_fees"),

    path("announcements/", views.announcements, name="announcements"),
    path("announcements/add/", views.announcement_create, name="announcement_create"),
    path("messages/", views.messages_view, name="messages"),
    path("messages/new/", views.message_create, name="message_create"),
    path("notifications/", views.notifications, name="notifications"),
    path("notifications/<int:pk>/read/", views.notification_read, name="notification_read"),
    path("events/", views.events, name="events"),
    path("events/add/", views.event_create, name="event_create"),
    path("search/", views.global_search, name="search"),
    path("profile/", views.profile, name="profile"),
]
